development:
  adapter: postgresql
  encoding: unicode
  database: mystery-works_development
  pool: 5
  username: salbecker
  password:
  port: 5432
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: mystery-works_production
  pool: 5
  username: mystery-works
  password: